baseURL = "https://planetoid-reader.github.io"
languageCode = "en-us"
title = "Personal Blog"

theme = "hugo-theme-console"

paginate = 5000 #frontpage pagination
#disqusShortname = "planetoidreader"



[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"

  # Comments
  # utterances, see: https://utteranc.es/
  #utterancesRepo = "planetoid-reader.gihub.io"
  utterancesRepo = "planetoid-reader.gihub.io"
  utterancesIssueTerm = "pathname"

[outputs]
  home = ["HTML", "RSS", "JSON"]